# Header
menu:
  主页: /
  所有文章: /archives
  生活: /tags/生活
  杂谈: /tags/杂谈
  知识小集: /tags/知识小集
  
# SubNav
subnav:
  github: "https://github.com/SharonHu1990"
  weibo: "http://weibo.com/sharonhu0813"
#  rss: "/atom.xml"
  #douban: "#"
#  mail: sharonhu0813@163.com
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
#  about: "/about"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /sun.ico

#你的头像url
avatar: /assets/blogImg/sun.png
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  我的LOFTER: http://sharon0325.lofter.com/
  我的CSDN: http://blog.csdn.net/dreamersharon

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 目前从事iOS开发，喜欢安静，爱好摄影、画画、唱歌，但是都不精通。只想当有意思的人，做有意思的事儿。